/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgenticFrameworkRouteImport } from './routes/agentic-framework'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalTransformationRouteImport } from './routes/digital-transformation'
import { Route as DistinguishedProductRouteImport } from './routes/distinguished-product'
import { Route as StrategicConsultingRouteImport } from './routes/strategic-consulting'
import { Route as IndexRouteImport } from './routes/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticFrameworkRoute = AgenticFrameworkRouteImport.update({
  id: '/agentic-framework',
  path: '/agentic-framework',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTransformationRoute = DigitalTransformationRouteImport.update({
  id: '/digital-transformation',
  path: '/digital-transformation',
  getParentRoute: () => rootRouteImport,
} as any)
const DistinguishedProductRoute = DistinguishedProductRouteImport.update({
  id: '/distinguished-product',
  path: '/distinguished-product',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategicConsultingRoute = StrategicConsultingRouteImport.update({
  id: '/strategic-consulting',
  path: '/strategic-consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agentic-framework': typeof AgenticFrameworkRoute
  '/contact': typeof ContactRoute
  '/digital-transformation': typeof DigitalTransformationRoute
  '/distinguished-product': typeof DistinguishedProductRoute
  '/strategic-consulting': typeof StrategicConsultingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agentic-framework': typeof AgenticFrameworkRoute
  '/contact': typeof ContactRoute
  '/digital-transformation': typeof DigitalTransformationRoute
  '/distinguished-product': typeof DistinguishedProductRoute
  '/strategic-consulting': typeof StrategicConsultingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agentic-framework': typeof AgenticFrameworkRoute
  '/contact': typeof ContactRoute
  '/digital-transformation': typeof DigitalTransformationRoute
  '/distinguished-product': typeof DistinguishedProductRoute
  '/strategic-consulting': typeof StrategicConsultingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agentic-framework'
    | '/contact'
    | '/digital-transformation'
    | '/distinguished-product'
    | '/strategic-consulting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agentic-framework'
    | '/contact'
    | '/digital-transformation'
    | '/distinguished-product'
    | '/strategic-consulting'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agentic-framework'
    | '/contact'
    | '/digital-transformation'
    | '/distinguished-product'
    | '/strategic-consulting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StrategicConsultingRoute: typeof StrategicConsultingRoute
  DigitalTransformationRoute: typeof DigitalTransformationRoute
  DistinguishedProductRoute: typeof DistinguishedProductRoute
  AgenticFrameworkRoute: typeof AgenticFrameworkRoute
  ContactRoute: typeof ContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentic-framework': {
      id: '/agentic-framework'
      path: '/agentic-framework'
      fullPath: '/agentic-framework'
      preLoaderRoute: typeof AgenticFrameworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-transformation': {
      id: '/digital-transformation'
      path: '/digital-transformation'
      fullPath: '/digital-transformation'
      preLoaderRoute: typeof DigitalTransformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distinguished-product': {
      id: '/distinguished-product'
      path: '/distinguished-product'
      fullPath: '/distinguished-product'
      preLoaderRoute: typeof DistinguishedProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategic-consulting': {
      id: '/strategic-consulting'
      path: '/strategic-consulting'
      fullPath: '/strategic-consulting'
      preLoaderRoute: typeof StrategicConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StrategicConsultingRoute: StrategicConsultingRoute,
  DigitalTransformationRoute: DigitalTransformationRoute,
  DistinguishedProductRoute: DistinguishedProductRoute,
  AgenticFrameworkRoute: AgenticFrameworkRoute,
  ContactRoute: ContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
